---
namespace: monitoring-system
promLabels:
  release: kube-prometheus-stack

homeTLD: home.ds

synology:
  name: ds920
  monitorSvc: ext_synology
nyarlathotep:
  name: nyarlathotep
  monitorSvc: ext_nya
  driveTemp:
    for: 10m
    zones:
      backup:
        title: Backup
        model: "WD Red SN700 4000GB"
        critical: 65
      fdd:
        title: FDD
        model: "Samsung SSD 970 EVO Plus 2TB"
        critical: 65
ha:
  name: homeassistant
  monitorSvc: smarthome
  noEntitiesFor: 30m
  qingping:
    sensorCount: 4
    CO2NotReportingFor: 2h
    noEntitiesFor: 2h
  ups:
    batteryThreshold: 95
  rtl_tfa:
    sensorCount: 11  # 8x KlimaloggPro + 1x Marbella + 1x Wind/Temp + 1x Rain
    noEntitiesFor: 6h

thermalAlerts:
  monitorSvc: thermal
  for: 5m
  zones:
    nvme:
      title: NVMe
      chip: nvme_nvme0
      critical: 78
      warning: 73
    core:
      title: Core
      chip: thermal_thermal_zone0
      critical: 85
      warning: 80

mikrotik:
  monitorSvc: network
  latencyWarningAnycast:
    for: 15m
    threshold: 50  # ms
    severity: warning
  lossWarningAnycast:
    for: 15m
    threshold: 20  # %
    severity: warning
  localDeviceDown:
    for: 30m
    severity: warning
